---
title: "Biomedical Publications"
subtitle: "The developmental role of Williams Syndrome Transcription Factor (WSTF)"
excerpt: "Williams Syndrome Transcription Factor (WSTF) exists in several chromatin remodeling complexes and has roles in the epigenetic control of transcription, replication, and repair. Chromatin remodeling is essential during embryogenesis, but WSTF’s role in vertebrate development is poorly characterized. These publications helped describe a role for WSTF in proper neural crest function during vertebrate development."
author: "Chris Barnett"
date: 2012-09-12
output: html_document
draft: false
tags:
  - hugo-site
layout: single
links:
- icon: door-open
  icon_pack: fas
  name: First Publication
  url: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3251257/
- icon: door-open
  icon_pack: fas
  name: Second Publication
  url: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3459152/ 
---

After completing my undergraduate degree in "*Molecular, Cellular, and Developmental Biology (MCDB)*," I pursued a master's degree in Biological Sciences, where I studied the epigenetic chromatin remodeler, Williams Syndrome Transcription Factor (WSTF), which emerged as an incredibly versatile nuclear protein. My research helped describe a role for WSTF in proper neural crest function during vertebrate development and led to two first-author publications and an [award-winning](https://wagsonline.org/outstanding-thesis-stem-award/) thesis.

Although I have pivoted from biomedical research to public health, I have brought many lessons and transferable skills that I learned as a graduate student in the lab. Critical thinking, experimental design, and communicating complex ideas are just some of the skills I sharpened while obtaining my MS.

